---@class UnitIds
local UnitIds = {
    abomination = 'uabo', -- model: Abomination	 scale: 0,9	 selectScale: 2,1
    abominationcinematic = 'uabc', -- model: AbominationCIN	 scale: 0,9	 selectScale: 2,1
    acolyte = 'uaco', -- model: Acolyte	
    admiralproudmoore = 'Hapm', -- model: Proudmoore	 scale: 1,1	 selectScale: 1,1
    airbarge = 'uarb', -- model: UndeadAirBarge	 selectScale: 2  
    akama = 'Naka', -- model: DranaiAkama	 scale: 1,5	 selectScale: 1,75
    albatross = 'nalb', -- model: Albatross	 scale: 1,2	 selectScale: 0,8
    alchemist = 'Nalc', -- model: HeroGoblinAlchemist	 selectScale: 2  
    alchemistmorph = 'Nalm', -- model: HeroGoblinAlchemist	 selectScale: 2  
    alchemistmorph2 = 'Nal2', -- model: HeroGoblinAlchemist	 selectScale: 2  
    alchemistmorph3 = 'Nal3', -- model: HeroGoblinAlchemist	 selectScale: 2  
    altarofdarkness = 'uaod', -- model: AltarOfDarkness	 selectScale: 4,25  
    altarofelders = 'eate', -- model: AltarOfElders	 selectScale: 4  
    altarofkings = 'halt', -- model: AltarofKings	 selectScale: 4  
    altarofstorms = 'oalt', -- model: AltarofStorms	 selectScale: 4,5  
    altarofthedepths = 'nnad', -- model: AltarOfDepths	 selectScale: 4  
    amphibioussheep = 'nsha', -- model: Sheep	 scale: 1,2	 selectScale: 0,9
    ancienthydra = 'nahy', -- model: Hydra	 scale: 1,55	 selectScale: 3
    ancientoflore = 'eaoe', -- model: AncientOfLore	 selectScale: 4  
    ancientofwar = 'eaom', -- model: AncientOfWar	 selectScale: 4  
    ancientofwind = 'eaow', -- model: AncientOfWind	 selectScale: 4  
    ancientofwonders = 'eden', -- model: AncientOfWonder	 selectScale: 4,5  
    ancientprotector = 'etrp', -- model: AncientProtector	 selectScale: 3  
    ancientsasquatch = 'nsqa', -- model: Sasquatch	 scale: 1,6	 selectScale: 1,45
    ancientwendigo = 'nwna', -- model: Wendigo	 scale: 1,65	 selectScale: 1,5
    antonidus = 'Hant', -- model: HeroArchMage	 selectScale: 1,5  
    anubarak = 'Uanb', -- model: Anubarak	 selectScale: 1,85  
    apprenticewizard = 'nwiz', -- model: HumanMage	
    arcaneobservatory = 'haro', -- model: ArcaneObservatory	 selectScale: 6,3  
    arcanesanctum = 'hars', -- model: ArcaneSanctum	 selectScale: 3,75  
    arcanevault = 'hvlt', -- model: ArcaneVault	 selectScale: 4,5  
    archer = 'earc', -- model: Archer	
    archimonde = 'Uwar', -- model: Warlock	 scale: 1,4	 selectScale: 2,1
    archmage = 'Hamg', -- model: HeroArchMage	 selectScale: 1,5  
    arthas = 'Hart', -- model: Arthas	 scale: 1,1	 selectScale: 1,1
    arthaswithfrostmourne = 'Harf', -- model: ArthaswithSword	 scale: 1,1	 selectScale: 1,1
    assassin = 'nass', -- model: BanditSpearThrower	 scale: 1,3  
    azuredragon = 'nadr', -- model: AzureDragon	 scale: 1,75	 selectScale: 2,25
    azuredragonwhelp = 'nadw', -- model: AzureDragonWelp	 scale: 0,7	 selectScale: 1,75
    azuredrake = 'nadk', -- model: AzureDragon	 scale: 1,2	 selectScale: 2
    azurelordfrostwyrm = 'ubdd', -- model: FrostWyrm	 scale: 2	 selectScale: 2,5
    azureloredragon = 'ubdr', -- model: AzureDragon	 scale: 2,25	 selectScale: 2,7
    balnazzar = 'Ubal', -- model: Tichondrius	 scale: 1,6	 selectScale: 1,9
    bandit = 'nban', -- model: Bandit	
    banditlord = 'nbld', -- model: BanditLord	 scale: 1,3	 selectScale: 1,25
    banshee = 'uban', -- model: Banshee	
    barbedarachnathid = 'nanb', -- model: Archnathid	 scale: 0,65	 selectScale: 1,4
    barbedarachnathidburrowed = 'nbnb', -- model: Archnathid	 scale: 0,65	 selectScale: 1,4
    barbedarachnathidmerc = 'nanm', -- model: Archnathid	 scale: 0,65	 selectScale: 1,4
    barrowden = 'nbwd', -- model: BarrowDens	 selectScale: 4,2  
    battlegolem = 'narg', -- model: GolemStatue	 scale: 0,8	 selectScale: 1,5
    battleship = 'nbsp', -- model: Battleship	 selectScale: 4  
    beastiary = 'obea', -- model: Beastiary	 selectScale: 4,5  
    beastmaster = 'Nbst', -- model: Beastmaster	 selectScale: 2  
    bereserkelemental = 'nelb', -- model: WaterElemental	 scale: 1,4	 selectScale: 1,6
    berserker = 'otbk', -- model: HeadHunter	 scale: 1,15	 selectScale: 1,1
    berserkowlbear = 'nowk', -- model: Owlbear	 scale: 1,6	 selectScale: 2,3
    bindstonese = 'nbse', -- model: RessurectionStoneSE	 selectScale: 3,5  
    bindstonesw = 'nbsw', -- model: RessurectionStoneSW	 selectScale: 3,5  
    blackdragon = 'nbwm', -- model: BlackDragon	 scale: 1,75	 selectScale: 2,25
    blackdragonroost = 'ndrk', -- model: DragonBuildingBlack	 scale: 1,5	 selectScale: 6,6
    blackdragonwhelp = 'nbdr', -- model: BlackDragonWelp	 scale: 0,7	 selectScale: 1,75
    blackdrake = 'nbdk', -- model: BlackDragon	 selectScale: 2  
    blackrockblademaster = 'Nbbc', -- model: HeroChaosBladeMaster	 selectScale: 1,15  
    blacksmith = 'hbla', -- model: Blacksmith	 selectScale: 4  
    blademaster = 'Obla', -- model: HeroBladeMaster	 selectScale: 1,25  
    bloodelfengineer = 'nbee', -- model: HighElfPeasant	
    bloodelflieutenant = 'nbel', -- model: BloodElfLieutenant	 selectScale: 1,2  
    bloodelfwagon = 'hbew', -- model: BloodElfWagon	 selectScale: 2,5  
    bloodelfworker = 'nhew', -- model: HighElfPeasant	
    bloodfiend = 'nfgb', -- model: Felgaurd	 scale: 1,35	 selectScale: 1,35
    bloodfountain = 'nbfl', -- model: FountainOfLifeBlood	 selectScale: 5  
    bloodmage = 'Hblm', -- model: HeroBloodElf	 selectScale: 1,5  
    bluedragonroost = 'ndru', -- model: DragonBuildingBlue	 scale: 1,5	 selectScale: 6,6
    bluedragonspawnapprentice = 'nbda', -- model: DragonSpawnGreen	 scale: 0,9	 selectScale: 1,8
    bluedragonspawnmeddler = 'nbdm', -- model: DragonSpawnBlue	 scale: 0,9	 selectScale: 1,8
    bluedragonspawnoverseer = 'nbdo', -- model: DragonSpawnBlue	 scale: 1,4	 selectScale: 2,5
    bluedragonspawnsorceror = 'nbds', -- model: DragonSpawnGreen	 scale: 1,3	 selectScale: 2,4
    bluedragonspawnwarrior = 'nbdw', -- model: DragonSpawnPurple	 scale: 1,15	 selectScale: 2,2
    boneyard = 'ubon', -- model: BoneYard	 selectScale: 5  
    bookofsummoning = 'nbsm', -- model: BookOfSummoning	 selectScale: 2,5  
    bouldertower = 'nbt1', -- model: TowerDefenseTower	 selectScale: 2,5  
    bouldertowerupgrade = 'nbt2', -- model: TowerDefenseTower	 selectScale: 2,5  
    brigand = 'nbrg', -- model: BanditSpearThrower	 scale: 1,1  
    bronzedragon = 'nbzd', -- model: BronzeDragon	 scale: 1,75	 selectScale: 2,25
    bronzedragonroost = 'ndrz', -- model: DragonRoost	 scale: 1,5	 selectScale: 6,6
    bronzedragonwhelp = 'nbzw', -- model: BronzeDragonWelp	 scale: 0,7	 selectScale: 1,75
    bronzedrake = 'nbzk', -- model: BronzeDragon	 scale: 1,2	 selectScale: 2
    broodmother = 'nsbm', -- model: SpiderBlue	 scale: 1,5	 selectScale: 1,5
    burningarcher = 'nskf', -- model: SkeletonArcher	 scale: 1,3  
    cairnebloodhoof = 'Ocbh', -- model: HeroTaurenChieftainCIN	 selectScale: 2  
    cairnebloodhoofcinematic = 'Otcc', -- model: HeroTaurenChieftainCIN	 selectScale: 2  
    cairnebloodhoofexp = 'Ocb2', -- model: HeroTaurenChieftainCIN	 selectScale: 2  
    campaignturtle = 'nhyc', -- model: DragonSeaTurtleRange	 scale: 0,8	 selectScale: 2,5
    cannontower = 'hctw', -- model: HumanTower	 selectScale: 2,5  
    cantina = 'ntav', -- model: Tavern	 selectScale: 6  
    carrionscarab1 = 'ucs1', -- model: scarab	 scale: 0,9	 selectScale: 1,25
    carrionscarab2 = 'ucs2', -- model: scarab	 scale: 1,1	 selectScale: 1,5
    carrionscarab3 = 'ucs3', -- model: scarab	 scale: 1,3	 selectScale: 1,75
    carrionscarabburrowed2 = 'ucsB', -- model: scarab	 scale: 1,1	 selectScale: 1,5
    carrionscarabburrowed3 = 'ucsC', -- model: scarab	 scale: 1,3	 selectScale: 1,75
    castle = 'hcas', -- model: TownHall	 selectScale: 6,3  
    cenarius = 'Ecen', -- model: HeroKeeperoftheGrove	 scale: 1,4	 selectScale: 3
    centaurarcher = 'ncea', -- model: CentaurArcher	 selectScale: 1,25  
    centaurdrudge = 'ncer', -- model: Centaur	 scale: 1,1  
    centaurimpaler = 'ncim', -- model: CentaurArcher	 scale: 1,35	 selectScale: 1,25
    centaurkhan = 'ncnk', -- model: CentaurKhan	 scale: 1,75	 selectScale: 1,85
    centauroutrunner = 'ncen', -- model: Centaur	 scale: 1,45	 selectScale: 1,25
    centaursorceror = 'ncks', -- model: CentaurKhan	 scale: 1,3	 selectScale: 1,4
    centaurtent = 'ncnt', -- model: CentaurTent	 selectScale: 3,5  
    centaurtent1 = 'nct1', -- model: CentaurTent1	 selectScale: 3,5  
    centaurtent2 = 'nct2', -- model: CentaurTent2	 selectScale: 3,5  
    chaosgrunt = 'nchg', -- model: ChaosGrunt	 scale: 1,2  
    chaoskotobeast = 'nckb', -- model: ChaosKotoBeast	 selectScale: 2,25  
    chaosorcburrow = 'ocbw', -- model: TrollBurrow	 selectScale: 2,75  
    chaospeon = 'ncpn', -- model: ChaosPeon	
    chaosspaceorc = 'zcso', -- model: ChaosSpaceOrc	
    chaoswarlock = 'nchw', -- model: ChaosWarlock	 selectScale: 1,15  
    chaoswarlord = 'owar', -- model: ChaosWarlord	
    chaoswolfrider = 'nchr', -- model: ChaosWolfRider	 scale: 1,2	 selectScale: 1,6
    chaplain = 'nchp', -- model: HumanMage	
    chicken = 'nech', -- model: EasterChicken	 selectScale: 0,9  
    chieftainhut = 'ndch', -- model: ChieftainHut	 selectScale: 2,5  
    chimaera = 'echm', -- model: Chimaera	 selectScale: 2  
    chimaeraroost = 'edos', -- model: ChimaeraRoost	 selectScale: 4  
    circleofpower = 'ncop', -- model: CircleOfPower	 selectScale: 3,5  
    circleofpowerlarge = 'ncp3', -- model: CircleOfPower	 scale: 2	 selectScale: 4,5
    circleofpowermedium = 'ncp2', -- model: CircleOfPower	 scale: 1,5	 selectScale: 4
    cityBuildingLarge0 = 'ncbc', -- model: CityBuildingLarge_0	 selectScale: 4  
    cityBuildingLarge1 = 'ncbd', -- model: CityBuildingLarge_45	 selectScale: 4  
    cityBuildingLarge2 = 'ncbe', -- model: CityBuildingLarge_90	 selectScale: 4  
    cityBuildingLarge3 = 'ncbf', -- model: CityBuildingLarge_135	 selectScale: 4  
    citybuildingSmall0 = 'ncb0', -- model: CityBuildingSmall45_0	 selectScale: 4  
    citybuildingSmall1 = 'ncb1', -- model: CityBuildingSmall45_1	 selectScale: 4  
    citybuildingSmall2 = 'ncb2', -- model: CityBuildingSmall45_2	 selectScale: 4  
    citybuildingSmall3 = 'ncb3', -- model: CityBuildingSmall90_0	 selectScale: 4  
    citybuildingSmall4 = 'ncb4', -- model: CityBuildingSmall90_1	 selectScale: 4  
    citybuildingSmall5 = 'ncb5', -- model: CityBuildingSmall90_2	 selectScale: 4  
    citybuildingSmall6 = 'ncb6', -- model: CityBuildingSmall135_0	 selectScale: 4  
    citybuildingSmall7 = 'ncb7', -- model: CityBuildingSmall135_1	 selectScale: 4  
    citybuildingSmall8 = 'ncb8', -- model: CityBuildingSmall135_2	 selectScale: 4  
    citybuildingSmall9 = 'ncb9', -- model: CityBuildingSmall0_0	 selectScale: 4  
    citybuildingSmalla = 'ncba', -- model: CityBuildingSmall0_1	 selectScale: 4  
    citybuildingSmallb = 'ncbb', -- model: CityBuildingSmall0_2	 selectScale: 4  
    clockwerkgoblin1 = 'ncgb', -- model: HeroTinkerRobot	 selectScale: 1,15  
    clockwerkgoblin2 = 'ncg1', -- model: HeroTinkerRobot	 selectScale: 1,15  
    clockwerkgoblin3 = 'ncg2', -- model: HeroTinkerRobot	 selectScale: 1,15  
    clockwerkgoblin4 = 'ncg3', -- model: HeroTinkerRobot	 selectScale: 1,15  
    coldtower = 'ndt1', -- model: TowerDefenseTower	 selectScale: 2,5  
    coldtowerupgrade = 'ndt2', -- model: TowerDefenseTower	 selectScale: 2,5  
    coralbed = 'nnfm', -- model: CoralBed	 selectScale: 3  
    corruptedancientofwar = 'ncaw', -- model: CorruptedAncientofWar	 selectScale: 4  
    corruptedancientprotector = 'ncap', -- model: CorruptedAncientProtector	 selectScale: 4  
    corruptedent = 'nenc', -- model: CorruptedEnt	 scale: 0,9  
    corruptedmoonwell = 'ncmw', -- model: CorruptedMoonWell	 selectScale: 3  
    corruptedtreeofages = 'ncta', -- model: CorruptedTreeofLife	 scale: 1,15	 selectScale: 4,75
    corruptedtreeofeternity = 'ncte', -- model: CorruptedTreeofLife	 scale: 1,3	 selectScale: 4,75
    corruptedtreeoflife = 'nctl', -- model: CorruptedTreeofLife	 selectScale: 4,75  
    crab = 'ncrb', -- model: SpiderCrab	 selectScale: 0,9  
    crypt = 'usep', -- model: Crypt	 selectScale: 5  
    cryptfiend = 'ucry', -- model: CryptFiend	 scale: 0,9	 selectScale: 1,85
    cryptfiendmorph = 'ucrm', -- model: CryptFiend	 scale: 0,9	 selectScale: 1,85
    cryptlord = 'Ucrl', -- model: HeroCryptLord	 selectScale: 1,85  
    crystalarachnathid = 'nanc', -- model: ArchnathidGreen	 scale: 0,65	 selectScale: 1,2
    dagren = 'Hdgo', -- model: HeroPaladinBoss2	 selectScale: 1,1  
    dalaranguardtower = 'ndgt', -- model: DalaranGuardTower	 selectScale: 2,5  
    dalaranmutant = 'ndmu', -- model: DalaranMutant	 scale: 1,75	 selectScale: 1,1
    dalaranreject = 'ndrj', -- model: DalaranReject	 scale: 1,15	 selectScale: 1,45
    darkminion1 = 'ndr1', -- model: Skeleton	
    darkminion2 = 'ndr2', -- model: Skeleton	 scale: 1,2	 selectScale: 1,2
    darkminion3 = 'ndr3', -- model: Skeleton	 scale: 1,4	 selectScale: 1,4
    darkportalse = 'ndke', -- model: DarkPortal2	 selectScale: 8,5  
    darkportalsw = 'ndkw', -- model: DarkPortal	 selectScale: 8,5  
    darkranger = 'Nbrn', -- model: BansheeRanger	 selectScale: 1,5  
    darktroll = 'ndtr', -- model: DarkTroll	 scale: 0,85  
    darktrollberserker = 'ndtb', -- model: DarkTroll	 scale: 1,3	 selectScale: 1,5
    darktrollhighpriest = 'ndth', -- model: DarkTrollShadowPriest	 scale: 1,25	 selectScale: 1,5
    darktrollshadowpriest = 'ndtp', -- model: DarkTrollShadowPriest	 scale: 0,9	 selectScale: 1,5
    darktrolltrapper = 'ndtt', -- model: DarkTrollTrapper	 scale: 1,15  
    darktrollwarlord = 'ndtw', -- model: DarkTrollTrapper	 scale: 1,6	 selectScale: 2
    darkwizard = 'nwzd', -- model: BanditMage	 scale: 1,2	 selectScale: 1,5
    deathknight = 'Udea', -- model: HeroDeathKnight	 selectScale: 1,85  
    deathrevenant = 'nrvd', -- model: Revenant	 scale: 1,5	 selectScale: 1,2
    deathtower = 'ntt1', -- model: TowerDefenseTower	 selectScale: 2,5  
    deathtowerupgrade = 'ntx2', -- model: TowerDefenseTower	 selectScale: 2,5  
    deceiver = 'nhdc', -- model: Acolyte	 scale: 1,2	 selectScale: 1,1
    deeplordrevenant = 'nlrv', -- model: RevenantOfTheWaves	 scale: 1,6  
    deer = 'nder', -- model: BlackStagMale	 scale: 1,5	 selectScale: 1,1
    defiledfountainoflife = 'ndfl', -- model: FountainOfLifeDefiled	 selectScale: 5  
    demolisher = 'ocat', -- model: catapult	 selectScale: 2,75  
    demolisherdraenei = 'ncat', -- model: catapult	 selectScale: 2,75  
    demongate = 'ndmg', -- model: DemonGate	 selectScale: 5  
    demonhunter = 'Edem', -- model: HeroDemonHunter	 selectScale: 1,5  
    demonhuntermorphed = 'Edmm', -- model: HeroDemonHunter	 selectScale: 2  
    detheroc = 'Udth', -- model: HeroDreadLord	 scale: 1,4	 selectScale: 1,75
    diremammoth = 'nmdr', -- model: MammothBlack	 scale: 1,25	 selectScale: 2,5
    direwolf = 'nwld', -- model: DireWolf	 scale: 1,2	 selectScale: 1,3
    dog = 'ndog', -- model: BrownWolf	
    doomguard = 'nbal', -- model: DoomGuard	 scale: 1,3	 selectScale: 2
    doomguardsummoned = 'nba2', -- model: DoomGuard	 scale: 1,3	 selectScale: 2
    draeneidarkslayer = 'ndrd', -- model: DranaiWhite	 scale: 1,15	 selectScale: 1,25
    draeneidisciple = 'ndrm', -- model: DranaiMage	 scale: 0,8	 selectScale: 0,85
    draeneiguardian = 'ndrf', -- model: Dranai	 scale: 0,8	 selectScale: 0,85
    draeneiharbinger = 'ndrh', -- model: DranaiMage	 selectScale: 1,05  
    draeneihaven = 'ndh2', -- model: ChieftainHut	 scale: 1,2	 selectScale: 4,25
    draeneilaborer = 'ndrl', -- model: Dranai	 scale: 0,8	 selectScale: 0,8
    draeneiprotector = 'ndrp', -- model: DranaiWhite	 scale: 0,9	 selectScale: 0,95
    draeneisalamander = 'ndsa', -- model: ThunderLizardVizier	 scale: 0,9	 selectScale: 2
    draeneiseer = 'ndrs', -- model: DranaiMage	 scale: 1,1	 selectScale: 1,25
    draeneiseerden = 'ndh4', -- model: DraneiHut1	 scale: 1,2	 selectScale: 4,25
    draeneistalker = 'ndrt', -- model: Dranai	 selectScale: 1,2  
    draeneivindicator = 'ndrn', -- model: DranaiWhite	 scale: 1,15	 selectScale: 1,25
    draeneiwarriorshall = 'ndh3', -- model: DraneiHut0	 scale: 1,2	 selectScale: 4,25
    draeneiwatcher = 'ndrw', -- model: Dranai	 selectScale: 1,05  
    dragonbuilding = 'ndrb', -- model: DragonBuilding	 selectScale: 3,5  
    dragonhawk = 'hdhw', -- model: BloodElfDragonHawk	 selectScale: 1,5  
    dragonturtle = 'ntrd', -- model: DragonSeaTurtle	 scale: 1,2	 selectScale: 4
    drakthul = 'odkt', -- model: OrcWarlockRed	 scale: 1,2	 selectScale: 1,25
    draneihut0 = 'ndh0', -- model: DraneiHut0	 selectScale: 2,5  
    draneihut1 = 'ndh1', -- model: DraneiHut1	 selectScale: 2,5  
    dreadlord = 'Udre', -- model: HeroDreadLord	 selectScale: 1,5  
    drekthar = 'Odrt', -- model: HeroFarSeer	 selectScale: 2  
    druidoftheclaw = 'edoc', -- model: DruidoftheClaw	 selectScale: 2  
    druidoftheclawmorphed = 'edcm', -- model: DruidoftheClaw	 selectScale: 2,5  
    druidofthetalon = 'edot', -- model: DruidoftheTalon	 selectScale: 1,25  
    druidofthetalonmorphed = 'edtm', -- model: DruidoftheTalon	 selectScale: 1,25  
    dryad = 'edry', -- model: Dryad	 selectScale: 1,25  
    duneworm = 'ndwm', -- model: DuneWorm	 selectScale: 0,9  
    earthborerarachnathid = 'nane', -- model: Archnathid	 selectScale: 1,7  
    earthfurytower = 'negf', -- model: ElvenGuardFireTower	 selectScale: 2,5  
    elderhydra = 'nehy', -- model: Hydra	 scale: 1,2	 selectScale: 2,5
    elderjunglestalker = 'njga', -- model: JungleBeast	 scale: 1,2	 selectScale: 1,45
    eldersasquatch = 'nsqe', -- model: SasquatchShaman	 selectScale: 1,2  
    eldervoidwalker = 'nvde', -- model: VoidWalker	 scale: 1,5	 selectScale: 1,5
    elderwendigo = 'nwnr', -- model: Wendigo	 scale: 1,3  
    elvenfarm = 'nefm', -- model: ElvenFarm	 selectScale: 3,5  
    elvenfarm0 = 'nef0', -- model: ElvenVillageBuilding0	 selectScale: 3,5  
    elvenfarm1 = 'nef1', -- model: ElvenVillageBuilding1	 selectScale: 3,5  
    elvenfarm2 = 'nef2', -- model: ElvenVillageBuilding2	 selectScale: 3,5  
    elvenfarm3 = 'nef3', -- model: ElvenVillageBuilding3	 selectScale: 3,5  
    elvenfarm4 = 'nef4', -- model: ElvenVillageBuilding4	 selectScale: 3,5  
    elvenfarm5 = 'nef5', -- model: ElvenVillageBuilding5	 selectScale: 3,5  
    elvenfarm6 = 'nef6', -- model: ElvenVillageBuilding6	 selectScale: 3,5  
    elvenfarm7 = 'nef7', -- model: ElvenVillageBuilding7	 selectScale: 3,5  
    elvenfishingvillage0 = 'nfv0', -- model: ElvenFishVillageBuilding0	 selectScale: 3,5  
    elvenfishingvillage1 = 'nfv1', -- model: ElvenFishVillageBuilding1	 selectScale: 3,5  
    elvenfishingvillage2 = 'nfv2', -- model: ElvenFishVillageBuilding2	 selectScale: 3,5  
    elvenfishingvillage3 = 'nfv3', -- model: ElvenFishVillageBuilding3	 selectScale: 3,5  
    elvenfishingvillage4 = 'nfv4', -- model: ElvenFishVillageBuilding4	 selectScale: 3,5  
    elvenguardtower = 'negt', -- model: ElvenGuardTower	 selectScale: 2,5  
    emissary = 'nemi', -- model: HumanMage	 scale: 1,1  
    energytower = 'net1', -- model: TowerDefenseTower	 selectScale: 2,5  
    energytowerupgrade = 'net2', -- model: TowerDefenseTower	 selectScale: 2,5  
    enforcer = 'nenf', -- model: Bandit	 scale: 1,45  
    engineergazlowe = 'negz', -- model: GoblinSapper	
    enragedelemental = 'nele', -- model: WaterElemental	 scale: 1,2	 selectScale: 1,6
    enragedowlbear = 'nowe', -- model: Owlbear	 scale: 1,4	 selectScale: 1,8
    enrangedjunglestalker = 'njgb', -- model: JungleBeast	 scale: 1,5	 selectScale: 1,7
    entangledgoldmine = 'egol', -- model: EntangledGoldMine	 selectScale: 5,5  
    eredardiabolist = 'nerd', -- model: EredarWarlockPurple	 scale: 1,65	 selectScale: 2
    eredarsorceror = 'ners', -- model: EredarWarlock	 scale: 1,4	 selectScale: 2
    eredarwarlock = 'nerw', -- model: EredarWarlock	 scale: 1,75	 selectScale: 2
    evilarthas = 'Uear', -- model: UndeadArthas	 selectScale: 1,85  
    evilillidan = 'Eevi', -- model: IllidanEvil	 selectScale: 1,5  
    evilillidandemonform = 'Eevm', -- model: IllidanEvil	 selectScale: 2  
    evilsylvanas = 'Usyl', -- model: EvilSylvanas	 selectScale: 1,5  
    facelessonedeathbringer = 'nfod', -- model: FacelessOne	 scale: 2,3	 selectScale: 2,4
    facelessoneterror = 'nfot', -- model: FacelessOne	 scale: 1,85	 selectScale: 2
    facelessonetrickster = 'nfor', -- model: FacelessOne	 scale: 1,4	 selectScale: 1,4
    faeriedragon = 'efdr', -- model: FaerieDragon	 selectScale: 1,5  
    fallenpriest = 'nhfp', -- model: Acolyte	 scale: 1,1  
    farm = 'hhou', -- model: Farm	 selectScale: 2,5  
    farseer = 'Ofar', -- model: HeroFarSeer	 selectScale: 2  
    felboar = 'nfbr', -- model: Felboar	 selectScale: 0,9  
    felguard = 'nfgu', -- model: Felgaurd	
    felravager = 'npfm', -- model: FelstalkerPurple	 scale: 1,5	 selectScale: 2,5
    felstalker = 'nfel', -- model: felhound	 selectScale: 1,5  
    firelord = 'Nfir', -- model: HeroFlameLord	 scale: 1,15	 selectScale: 2
    firerevenant = 'nrvf', -- model: Revenant	 scale: 0,9  
    flametower = 'nft1', -- model: TowerDefenseTower	 selectScale: 2,5  
    flametowerupgrade = 'nft2', -- model: TowerDefenseTower	 selectScale: 2,5  
    fleshgolem = 'nfgl', -- model: FleshGolem	 scale: 1,75	 selectScale: 3
    flyingmachine = 'hgyr', -- model: Gyrocopter	 selectScale: 1,5  
    flyingsheep = 'nshf', -- model: FlyingSheep	 scale: 1,2	 selectScale: 0,8
    footman = 'hfoo', -- model: Footman	
    forceofnature = 'efon', -- model: Ent	 selectScale: 1,5  
    forestspider = 'nspg', -- model: SpiderGreen	 scale: 0,6	 selectScale: 1,5
    foresttroll = 'nftr', -- model: ForestTroll	
    foresttrollberserker = 'nftb', -- model: ForestTroll	 scale: 1,25	 selectScale: 1,5
    foresttrollhighpriest = 'nfsh', -- model: ForestTrollShadowPriest	 scale: 1,25	 selectScale: 1,5
    foresttrollhut0 = 'nfh0', -- model: ForestTrollHut0	 selectScale: 3,5  
    foresttrollhut1 = 'nfh1', -- model: ForestTrollHut1	 selectScale: 3,5  
    foresttrollking = 'nftk', -- model: ForestTrollTrapper	 scale: 1,55	 selectScale: 2
    foresttrollshadowpriest = 'nfsp', -- model: ForestTrollShadowPriest	 scale: 1,05	 selectScale: 1,5
    foresttrolltrapper = 'nftt', -- model: ForestTrollTrapper	
    forgottenone = 'nfgo', -- model: ForgottenOne	 scale: 0,9	 selectScale: 4,3
    fortress = 'ofrt', -- model: GreatHall	 selectScale: 6,6  
    fountainofhealth = 'nfoh', -- model: FountainOfHealth	 selectScale: 5  
    fountainofmana = 'nmoo', -- model: FountainOfMana	 selectScale: 5  
    frog = 'nfro', -- model: Frog	 selectScale: 0,9  
    frostmourne = 'nfrm', -- model: Frostmourne	 selectScale: 2,5  
    frostrevenant = 'nrvs', -- model: Revenant	
    frosttower = 'uzg2', -- model: Ziggurat	 selectScale: 4,25  
    frostwyrm = 'ufro', -- model: FrostWyrm	 selectScale: 2,25  
    fruitstand = 'nfrt', -- model: FruitStand	 selectScale: 4  
    furbolg = 'nfrl', -- model: Furbolg	 scale: 1,15  
    furbolgancient = 'nfra', -- model: FurbolgElder	 scale: 1,4	 selectScale: 1,75
    furbolgchampion = 'nfrg', -- model: Furbolg	 scale: 1,3	 selectScale: 1,5
    furbolgeldershaman = 'nfre', -- model: FurbolgShaman	 scale: 1,25	 selectScale: 1,5
    furbolghut1 = 'nfr1', -- model: FurbolgHut	 selectScale: 3,5  
    furbolghut2 = 'nfr2', -- model: FurbolgHut2	 selectScale: 3,5  
    furbolgpanda = 'nfrp', -- model: FurbolgPanda	
    furbolgshaman = 'nfrs', -- model: FurbolgShaman	 scale: 0,9  
    furbolgtracker = 'nfrb', -- model: FurbolgTracker	 scale: 1,2  
    furion = 'Efur', -- model: Furion	 scale: 1,1	 selectScale: 1,25
    gargantuanseaturtle = 'ntrg', -- model: GiantSeaTurtle	 selectScale: 3  
    gargoyle = 'ugar', -- model: Gargoyle	 selectScale: 1,25  
    gargoylemorphed = 'ugrm', -- model: Gargoyle	 selectScale: 1,25  
    garthok = 'ogrk', -- model: Grunt	 scale: 1,1  
    gemstoneobelisk = 'ngob', -- model: BridgeObelisk	 selectScale: 2,5  
    ghost = 'ngh1', -- model: BansheeGhost	 scale: 1,05  
    ghostlyarchmage = 'Hgam', -- model: HeroArchMageGhost	 selectScale: 1,5  
    ghoul = 'ugho', -- model: Ghoul	 selectScale: 1,1  
    giantpolarbear = 'nplg', -- model: PolarBear	 scale: 1,3	 selectScale: 2,4
    giantseaturtle = 'ntrt', -- model: GiantSeaTurtleRange	 scale: 0,8	 selectScale: 2,5
    giantskeleton = 'nskg', -- model: Skeleton	 scale: 1,35  
    giantspider = 'nsgt', -- model: Spider	 scale: 1,25	 selectScale: 1,5
    giantwhitewolf = 'nwwg', -- model: WhiteWolf	 scale: 1,2	 selectScale: 1,5
    giantwolf = 'nwlg', -- model: TimberWolf	 scale: 1,1	 selectScale: 1,2
    glaivethrower = 'ebal', -- model: Ballista	 selectScale: 3  
    gnoll1 = 'ngno', -- model: Gnoll	
    gnoll3 = 'ngnw', -- model: GnollWarden	 scale: 1,5  
    gnollassassin = 'ngns', -- model: GnollArcher	 scale: 1,3  
    gnollbrute = 'ngnb', -- model: Gnoll	 scale: 1,3  
    gnollhut = 'ngnh', -- model: GnollHut	 selectScale: 3,5  
    gnollhut2 = 'ngt2', -- model: GnollHut2	 selectScale: 3,5  
    gnollking = 'ngnv', -- model: GnollOverseer	 scale: 1,75  
    gnollpoacher = 'ngna', -- model: GnollArcher	 scale: 0,9  
    goblinammodump = 'ngad', -- model: AmmoDump	 selectScale: 4,75  
    goblinblaster = 'ngbl', -- model: IronGolem	 selectScale: 1,75  
    goblinlandmine = 'nglm', -- model: GoblinLandMine	 selectScale: 0,75  
    goblinmerchant = 'ngme', -- model: Merchant	 selectScale: 4,5  
    goblinsapper = 'ngsp', -- model: GoblinSapper	
    goblinshipyard = 'nshp', -- model: GoblinShipyard	 selectScale: 4,75  
    goblinshredder = 'ngir', -- model: IronGolem	 selectScale: 1,75  
    goblinzeppelin = 'nzep', -- model: GoblinZeppelin	 selectScale: 1,5  
    goldmine = 'ngol', -- model: GoldMine	 selectScale: 5  
    grainwarehouse = 'ngwr', -- model: GrainWarehouse	 selectScale: 4  
    granaryinfected = 'ngni', -- model: GranaryInfected	 selectScale: 3,5  
    granitegolem = 'nggr', -- model: RockGolem	 scale: 1,5	 selectScale: 3
    graveyard = 'ugrv', -- model: Graveyard	 selectScale: 5  
    greatervoidwalker = 'nvdg', -- model: VoidWalker	 scale: 1,3	 selectScale: 1,3
    greathall = 'ogre', -- model: GreatHall	 selectScale: 6,6  
    greendragon = 'ngrd', -- model: GreenDragon	 scale: 1,75	 selectScale: 2,25
    greendragonroost = 'ndrg', -- model: DragonBuildingGreen	 scale: 1,5	 selectScale: 6,6
    greendragonwhelp = 'ngrw', -- model: GreenDragonWelp	 scale: 0,7	 selectScale: 1,75
    greendrake = 'ngdk', -- model: GreenDragon	 scale: 1,2	 selectScale: 2
    grizzlybear1 = 'ngz1', -- model: GrizzlyBear	 scale: 0,9	 selectScale: 1,25
    grizzlybear2 = 'ngz2', -- model: GrizzlyBear	 scale: 1,1	 selectScale: 1,5
    grizzlybear3 = 'ngz3', -- model: GrizzlyBear	 scale: 1,25	 selectScale: 1,75
    gromhellscream = 'Ogrh', -- model: Hellscream	 selectScale: 1,15  
    grunt = 'ogru', -- model: Grunt	 scale: 1,1  
    gryphonaviary = 'hgra', -- model: GryphonAviary	 selectScale: 4  
    gryphonrider = 'hgry', -- model: GryphonRider	 scale: 1,2	 selectScale: 1,5
    guardtower = 'hgtw', -- model: HumanTower	 selectScale: 2,5  
    guldan = 'Ogld', -- model: OrcWarlockGuldan	 selectScale: 1,4  
    halahk = 'Hhkl', -- model: HeroPaladinBoss	 selectScale: 1,1  
    harpyhag = 'nhrh', -- model: HarpyWitch	 scale: 1,7	 selectScale: 1,5
    harpynest = 'nhns', -- model: HarpyNest	 selectScale: 3,5  
    harpyqueen = 'nhrq', -- model: HarpyQueen	 scale: 2,1	 selectScale: 2
    harpyrogue = 'nhrr', -- model: Harpy	 scale: 1,7	 selectScale: 1,2
    harpyscout = 'nhar', -- model: Harpy	 selectScale: 1,2  
    harpywitch = 'nhrw', -- model: HarpyWitch	 selectScale: 1,2  
    headhunter = 'ohun', -- model: HeadHunter	 selectScale: 1,1  
    healingward = 'ohwd', -- model: HealingWard	 selectScale: 0,75  
    heretic = 'nhhr', -- model: Acolyte	 scale: 1,5	 selectScale: 1,25
    hermitcrab = 'nhmc', -- model: HermitCrab	 selectScale: 0,9  
    highelfbarracks = 'nheb', -- model: MageTower	 selectScale: 4  
    highelvenarcher = 'nhea', -- model: HighElfArcher	
    highelvenfemale = 'nhef', -- model: ElfVillagerWoman	
    highelvenmale = 'nhem', -- model: HighElfPeasant	
    highelvenswordsman = 'hhes', -- model: TheCaptain	 scale: 0,9	 selectScale: 1,2
    hippogryph = 'ehip', -- model: Hippogryph	 selectScale: 1,5  
    hornofcenarius = 'nhcn', -- model: HornOfCenarius	 selectScale: 2,5  
    humanarcanetower = 'hatw', -- model: HumanTower	 selectScale: 2,5  
    humanbarracks = 'hbar', -- model: HumanBarracks	 selectScale: 5  
    humanbattleship = 'hbsh', -- model: HumanBattleship	 selectScale: 4  
    humandestroyer = 'hdes', -- model: HumanDestroyerShip	 selectScale: 3  
    humanlumbermill = 'hlum', -- model: HumanLumbermill	 selectScale: 4,25  
    humanshipyard = 'hshy', -- model: HumanShipyard	 selectScale: 5  
    humantransportship = 'hbot', -- model: HumanTransportShip	 selectScale: 3  
    huntershall = 'edob', -- model: HuntersHall	 selectScale: 4,2  
    huntress = 'esen', -- model: Huntress	 selectScale: 1,5  
    hydra = 'nhyd', -- model: Hydra	 scale: 1,1	 selectScale: 2,5
    hydrahatchling = 'nhyh', -- model: Hydra	 scale: 0,75	 selectScale: 1,5
    hydralisk = 'zhyd', -- model: Hydralisk	 selectScale: 1,2  
    hydromancer = 'nhym', -- model: BanditMage	 scale: 0,9	 selectScale: 1,5
    icecrownobelisk = 'nico', -- model: IcecrownObelisk	 selectScale: 3,5  
    icerevenant = 'nrvi', -- model: Revenant	 scale: 1,3	 selectScale: 1,1
    icetroll = 'nitr', -- model: IceTroll	
    icetrollberserker = 'nits', -- model: IceTroll	 scale: 1,3  
    icetrollhighpriest = 'nith', -- model: IceTrollShadowPriest	 scale: 1,25  
    icetrollhut0 = 'nth0', -- model: IceTrollHut0	 selectScale: 3,5  
    icetrollhut1 = 'nth1', -- model: IceTrollHut1	 selectScale: 3,5  
    icetrollshadowpriest = 'nitp', -- model: IceTrollShadowPriest	 scale: 1,05  
    icetrolltrapper = 'nitt', -- model: IceTroll	
    icetrollwarlord = 'nitw', -- model: IceTroll	 scale: 1,55  
    icetuskmammoth = 'nmit', -- model: Mammoth	 scale: 1,05	 selectScale: 2,1
    illidan = 'Eill', -- model: HeroDemonHunter	 selectScale: 1,5  
    illidandemonform = 'Eidm', -- model: HeroDemonHunter	 selectScale: 2  
    illidanmorphed = 'Eilm', -- model: HeroDemonHunter	 selectScale: 2  
    illidanwagon = 'eilw', -- model: IllidanEvilCaged	 selectScale: 2,5  
    infernal = 'ninf', -- model: Infernal	 selectScale: 2,5  
    infernalcontraption = 'ninc', -- model: InfernalCannonCannon	 scale: 0,75	 selectScale: 2,25
    infernaljuggernaut = 'nina', -- model: InfernalCannonFlame	 scale: 1,5	 selectScale: 3,5
    infernalmachine = 'ninm', -- model: InfernalCannonCannon	 selectScale: 2,75  
    jailorkassan = 'njks', -- model: Bandit	 scale: 1,5	 selectScale: 1,25
    jaina = 'Hjai', -- model: Jaina	 selectScale: 1,5  
    juggernaut = 'ojgn', -- model: OrcJuggernaught	 selectScale: 4  
    junglestalker = 'njg1', -- model: JungleBeast	 selectScale: 1,1  
    kael = 'Hkal', -- model: Kael	 selectScale: 1,5  
    keep = 'hkee', -- model: TownHall	 selectScale: 6,3  
    keeperofthegrove = 'Ekee', -- model: HeroKeeperoftheGrove	 selectScale: 2,25  
    keeperofthegroveghost = 'Ekgg', -- model: HeroKeeperoftheGroveGhost	 selectScale: 2,25  
    kelthuzadghost = 'uktg', -- model: KelThuzadGhost	 scale: 1,15	 selectScale: 1,25
    kelthuzadlich = 'Uktl', -- model: HeroLich	 selectScale: 1,25  
    kelthuzadlichcinematic = 'Uclc', -- model: HeroLichCIN	 selectScale: 1,25  
    kelthuzadnecro = 'uktn', -- model: Kelthuzad	 scale: 1,15	 selectScale: 1,25
    kiljaeden = 'Nklj', -- model: Kiljaeden	 selectScale: 1,7  
    kiljaedencinematic = 'Nkjx', -- model: KiljaedenCinema	 selectScale: 3  
    knight = 'hkni', -- model: Knight	 selectScale: 1,4  
    kobold = 'nkob', -- model: Kobold	 scale: 0,85  
    koboldgeomancer = 'nkog', -- model: KoboldGeomancer	 scale: 1,4  
    koboldtaskmaster = 'nkol', -- model: Kobold	 scale: 1,6  
    kobolttunneler = 'nkot', -- model: Kobold	 scale: 1,25  
    kotobeast = 'okod', -- model: KotoBeast	 selectScale: 2,25  
    kotobeastnorider = 'oosc', -- model: KotoBeastNoRider	 selectScale: 2,5  
    ladyvashj = 'Hvsh', -- model: LadyVashj	 selectScale: 1,5  
    lavaspawn = 'nlv1', -- model: LavaSpawn	 scale: 0,8	 selectScale: 1,6
    lavaspawn2 = 'nlv2', -- model: LavaSpawn	 selectScale: 1,6  
    lavaspawn3 = 'nlv3', -- model: LavaSpawn	 scale: 1,2	 selectScale: 1,6
    lesservoidwalker = 'nvdl', -- model: VoidWalker	 scale: 0,75  
    lich = 'Ulic', -- model: HeroLich	 selectScale: 1,25  
    lichking = 'nzlc', -- model: lichking	 selectScale: 4  
    lightninglizard = 'nltl', -- model: ThunderLizard	 scale: 0,85	 selectScale: 2,5
    lightningrevenant = 'nrvl', -- model: Revenant	 scale: 1,1  
    lobstrokkdeepseer = 'nlds', -- model: Lobstrokkblue	 scale: 0,8	 selectScale: 1,75
    lobstrokkpooldweller = 'nlpd', -- model: Lobstrokkred	 scale: 0,6	 selectScale: 1,65
    lobstrokkprawn = 'nlpr', -- model: Lobstrokkred	 scale: 0,55	 selectScale: 1,4
    lobstrokkprawnsummoned = 'nlps', -- model: Lobstrokkred	 scale: 0,55	 selectScale: 1,4
    lobstrokksnapper = 'nlsn', -- model: Lobstrokkred	 scale: 0,8	 selectScale: 1,9
    lobstrokktidallord = 'nlkl', -- model: Lobstrokkgreen	 selectScale: 2,5  
    lobstrokktidecaller = 'nltc', -- model: Lobstrokkblue	 scale: 0,57	 selectScale: 1,5
    locust = 'uloc', -- model: Locust	
    lordgarithos = 'Hlgr', -- model: LordGarithos	 scale: 1,2	 selectScale: 1,6
    magicvault = 'nmgv', -- model: MagicVault	 selectScale: 3,3  
    magnataurdestroyer = 'nmgd', -- model: MagnataurBlue	 scale: 1,45	 selectScale: 3
    magnataurreaver = 'nmgr', -- model: Magnataur	 scale: 1,325	 selectScale: 2,75
    magnataurwarrior = 'nmgw', -- model: MagnataurBrown	 scale: 1,125	 selectScale: 2,25
    magtheridon = 'Nmag', -- model: HeroPitLord	 scale: 1,35	 selectScale: 3
    maidenofpain = 'ndqp', -- model: DemonessBlue	 scale: 1,4	 selectScale: 1,4
    maiev = 'Ewrd', -- model: Maiev	 selectScale: 1,5  
    malfurion = 'Emfr', -- model: MalFurion	 scale: 1,2	 selectScale: 2,25
    malfurionnostag = 'Emns', -- model: MalFurionNoStag	 scale: 1,2	 selectScale: 2,25
    malganis = 'Umal', -- model: HeroDreadLord	 selectScale: 1,5  
    mammoth = 'nmam', -- model: Mammoth	 scale: 0,85	 selectScale: 1,75
    mannoroth = 'Nman', -- model: Mannoroth	 scale: 1,7	 selectScale: 3
    margoth = 'Hmgd', -- model: HeroPaladin	 selectScale: 1,1  
    marine = 'zmar', -- model: Marine	
    marketplace = 'nmrk', -- model: Marketplace	 selectScale: 6  
    mathog = 'omtg', -- model: ChaosWarlord	
    meatwagon = 'umtw', -- model: MeatWagon	 selectScale: 2,5  
    medivh = 'nmed', -- model: Medivh	 selectScale: 1,25  
    medivhmorphed = 'nmdm', -- model: Medivh	 selectScale: 1,25  
    mercenarycampa = 'nmr5', -- model: Mercenary	 scale: 0,8	 selectScale: 6
    mercenarycampb = 'nmr4', -- model: Mercenary	 scale: 0,8	 selectScale: 6
    mercenarycampc = 'nmr6', -- model: Mercenary	 scale: 0,8	 selectScale: 6
    mercenarycampd = 'nmra', -- model: Mercenary	 scale: 0,8	 selectScale: 6
    mercenarycampf = 'nmr2', -- model: Mercenary	 scale: 0,8	 selectScale: 6
    mercenarycampg = 'nmrb', -- model: Mercenary	 scale: 0,8	 selectScale: 6
    mercenarycampi = 'nmrd', -- model: Mercenary	 scale: 0,8	 selectScale: 6
    mercenarycampk = 'nmrf', -- model: Mercenary	 scale: 0,8	 selectScale: 6
    mercenarycampl = 'nmer', -- model: Mercenary	 scale: 0,8	 selectScale: 6
    mercenarycampn = 'nmr7', -- model: Mercenary	 scale: 0,8	 selectScale: 6
    mercenarycampo = 'nmre', -- model: Mercenary	 scale: 0,8	 selectScale: 6
    mercenarycampv = 'nmr0', -- model: Mercenary	 scale: 0,8	 selectScale: 6
    mercenarycampw = 'nmr3', -- model: Mercenary	 scale: 0,8	 selectScale: 6
    mercenarycampx = 'nmr9', -- model: Mercenary	 scale: 0,8	 selectScale: 6
    mercenarycampy = 'nmr8', -- model: Mercenary	 scale: 0,8	 selectScale: 6
    mercenarycampz = 'nmrc', -- model: Mercenary	 scale: 0,8	 selectScale: 6
    militia = 'hmil', -- model: Militia	
    misha = 'nmsh', -- model: GrizzlyBear	 selectScale: 1,4  
    misha1 = 'ngzc', -- model: GrizzlyBear	 scale: 0,9	 selectScale: 1,75
    misha2 = 'ngzd', -- model: GrizzlyBear	 scale: 1,1	 selectScale: 2
    misha3 = 'ngza', -- model: GrizzlyBear	 scale: 1,2	 selectScale: 2,2
    misha4 = 'ngz4', -- model: GrizzlyBear	 scale: 1,3	 selectScale: 2,4
    monsterlure = 'nlur', -- model: MonsterLure	 selectScale: 0,75  
    moonwell = 'emow', -- model: MoonWell	 selectScale: 3  
    mortarteam = 'hmtm', -- model: MortarTeam	 selectScale: 1,3  
    mountaingiant = 'emtg', -- model: MountainGiant	 selectScale: 3  
    mountainking = 'Hmkg', -- model: HeroMountainKing	 selectScale: 1,25  
    mudgolem = 'ngrk', -- model: RockGolem	 scale: 0,6	 selectScale: 1,75
    muradinbronzebeard = 'Hmbr', -- model: Muradin	
    murgulbloodgill = 'nmbg', -- model: MurgulBloodGill	 scale: 0,9	 selectScale: 0,9
    murgulcliffrunner = 'nmcf', -- model: MurgulTideWarrior	 scale: 0,8	 selectScale: 0,8
    murgulhut0 = 'nmg0', -- model: MurlocHut0	 selectScale: 3,5  
    murgulhut1 = 'nmg1', -- model: MurlocHut1	 selectScale: 3,5  
    murgulreaver = 'nmrv', -- model: MurgulReaver	 scale: 1,5	 selectScale: 1,45
    murgulshadowcaster = 'nmsc', -- model: MurgulShadowCaster	 scale: 1,55	 selectScale: 1,5
    murgulslave = 'nmpe', -- model: MurgulSlave	
    murgulsnarecaster = 'nmsn', -- model: MurgulShadowCaster	 scale: 1,1	 selectScale: 1,1
    murgultidewarrior = 'nmtw', -- model: MurgulTideWarrior	
    murlocflesheater = 'nmfs', -- model: MurlocFlesheater	 scale: 1,55  
    murlochuntsman = 'nmrr', -- model: MurlocWarrior	 scale: 1,3  
    murlochut0 = 'nmh0', -- model: MurlocHut0	 selectScale: 3,5  
    murlochut1 = 'nmh1', -- model: MurlocHut1	 selectScale: 3,5  
    murlocmutant = 'nmmu', -- model: MurlocMutant	 scale: 2  
    murlocnightcrawler = 'nmrm', -- model: MurlocNightcrawler	 scale: 1,6  
    murlocplaguebearer = 'nmpg', -- model: MurlocMutant	
    murloctiderunner = 'nmrl', -- model: Murloc	
    nagacoutl = 'nwgs', -- model: WindSerpent	 scale: 0,7	 selectScale: 1,75
    nagamurgul = 'nnmg', -- model: MurgulReaver	 scale: 1,1	 selectScale: 1,15
    nagamyrmidon = 'nmyr', -- model: NagaMyrmidon	 selectScale: 1,75  
    nagamyrmidonmorph = 'nmys', -- model: NagaMyrmidon	 selectScale: 1,75  
    nagaroyalguard = 'nnrg', -- model: NagaRoyalGuard	 scale: 1,25	 selectScale: 2,25
    nagaroyalguardmorph = 'nnrs', -- model: NagaRoyalGuard	 scale: 1,25	 selectScale: 2,25
    naisha = 'ensh', -- model: Huntress	 scale: 1,2	 selectScale: 1,5
    nazgrel = 'onzg', -- model: WolfRider	 selectScale: 1,6  
    necromancer = 'unec', -- model: Necromancer	 selectScale: 1,25  
    necropolis = 'unpl', -- model: Necropolis	 selectScale: 6,6  
    necropolis1 = 'unp1', -- model: Necropolis	 selectScale: 6,6  
    necropolis2 = 'unp2', -- model: Necropolis	 selectScale: 6,6  
    nerubianqueen = 'nnwq', -- model: NerubianQueen	 scale: 1,6	 selectScale: 2
    nerubianseer = 'nnwr', -- model: NerubianQueen	 scale: 1,4	 selectScale: 1,8
    nerubianspiderlord = 'nnws', -- model: NerubianSpiderLord	 scale: 1,55	 selectScale: 1,8
    nerubianwarrior = 'nnwa', -- model: Nerubian	 scale: 1,2	 selectScale: 1,75
    nerubianwebspinner = 'nnwl', -- model: NerubianSpiderLord	 selectScale: 2  
    nerubianziggurat = 'nnzg', -- model: NerubianZiggurat	 selectScale: 3,5  
    netherdragon = 'nndr', -- model: NetherDragon	 scale: 1,35	 selectScale: 2
    netherdragonhatchling = 'nnht', -- model: NetherDragon	 scale: 0,65	 selectScale: 1,65
    netherdrake = 'nndk', -- model: NetherDragon	 scale: 1,05	 selectScale: 1,75
    nightelfassassin = 'nssn', -- model: assassin	 selectScale: 1,15  
    nightelfbattleship = 'ebsh', -- model: NightElfBattleship	 selectScale: 4  
    nightelfdestroyer = 'edes', -- model: NightElfDestroyerShip	 selectScale: 3  
    nightelfrunner = 'enec', -- model: Runner	
    nightelfshipyard = 'eshy', -- model: NightElfShipyard	 selectScale: 5  
    nightelftransportship = 'etrs', -- model: NightElfTransportShip	 selectScale: 3  
    obsidiandestroyer = 'ubsp', -- model: ObsidianStatue	 scale: 0,85	 selectScale: 1,5
    obsidianstatue = 'uobs', -- model: ObsidianStatue	 scale: 0,85	 selectScale: 2,1
    ogre1 = 'nogr', -- model: Ogre	 scale: 1,25	 selectScale: 1,2
    ogre2 = 'nogm', -- model: Ogre	 scale: 1,6	 selectScale: 1,2
    ogrelord = 'nogl', -- model: OgreLord	 scale: 1,7	 selectScale: 2
    ogremagi = 'nomg', -- model: OgreMagi	 scale: 1,4	 selectScale: 1,2
    oldpitlord = 'Npld', -- model: PitLord	 scale: 1,35	 selectScale: 3
    orcbarracks = 'obar', -- model: OrcBarracks	 selectScale: 4,5  
    orcishdestroyer = 'odes', -- model: OrcishDestroyerShip	 selectScale: 3  
    orcishtransportship = 'obot', -- model: OrcishTransportShip	 selectScale: 3  
    orcjuggernaut = 'zjug', -- model: OrcJuggernaught	
    orcshipyard = 'oshy', -- model: GoblinShipyard	 selectScale: 5  
    outlanddragonroost = 'ndro', -- model: DragonBuildingBlack	 scale: 1,5	 selectScale: 6,6
    overlord = 'nfov', -- model: FelgaurdBlue	 scale: 1,5	 selectScale: 1,5
    overlordarachnathid = 'nano', -- model: Archnathidpurple	 scale: 1,2	 selectScale: 1,8
    owl = 'nowl', -- model: OwlSCOUT	 scale: 1,2	 selectScale: 1,2
    owl2 = 'now2', -- model: OwlSCOUT	 scale: 1,2	 selectScale: 1,2
    owl3 = 'now3', -- model: OwlSCOUT	 scale: 1,2	 selectScale: 1,2
    owlbear = 'nowb', -- model: Owlbear	 scale: 1,2	 selectScale: 1,6
    packhorse = 'hrdh', -- model: PackHorse	 selectScale: 1,4  
    paladin = 'Hpal', -- model: HeroPaladin	 selectScale: 1,25  
    paladinboss1 = 'Hpb1', -- model: HeroPaladinBoss	 selectScale: 1,1  
    paladinboss2 = 'Hpb2', -- model: HeroPaladinBoss2	 selectScale: 1,1  
    panda1 = 'npn1', -- model: FirePandarenBrewmaster	 scale: 0,8	 selectScale: 1,4
    panda2 = 'npn2', -- model: StormPandarenBrewmaster	 scale: 0,8	 selectScale: 1,4
    panda3 = 'npn3', -- model: EarthPandarenBrewmaster	 scale: 0,9	 selectScale: 1,4
    panda4 = 'npn4', -- model: FirePandarenBrewmaster	 scale: 1,1	 selectScale: 1,7
    panda5 = 'npn5', -- model: StormPandarenBrewmaster	 scale: 1,1	 selectScale: 1,7
    panda6 = 'npn6', -- model: EarthPandarenBrewmaster	 scale: 1,2	 selectScale: 1,7
    pandarenbrewmaster = 'Npbm', -- model: PandarenBrewmaster	 selectScale: 2  
    peasant = 'hpea', -- model: Peasant	
    penguin = 'npng', -- model: Penguin	 selectScale: 0,9  
    peon = 'opeo', -- model: Peon	
    phoenix = 'hphx', -- model: phoenix	 selectScale: 1,5  
    phoenixegg = 'hpxe', -- model: phoenix	 scale: 1,25  
    pig = 'npig', -- model: Pig	 selectScale: 0,9  
    pigfarm = 'npgf', -- model: PigFarm	 selectScale: 2,75  
    pitlord = 'Nplh', -- model: HeroPitLord	 selectScale: 2,5  
    plagueent = 'nepl', -- model: CorruptedEnt	 scale: 1,4	 selectScale: 1,45
    plagueward = 'uplg', -- model: PlagueCloud	 selectScale: 0,75  
    pocketfactory = 'nfac', -- model: HeroTinkerFactory	 scale: 0,9	 selectScale: 3,3
    pocketfactory2 = 'nfa1', -- model: HeroTinkerFactory	 scale: 0,9	 selectScale: 3,3
    pocketfactory3 = 'nfa2', -- model: HeroTinkerFactory	 scale: 0,9	 selectScale: 3,3
    poisonent = 'nenp', -- model: CorruptedEnt	 scale: 1,25	 selectScale: 1,35
    polarbear = 'nplb', -- model: PolarBear	 scale: 0,95	 selectScale: 1,8
    polarfurbolg = 'nfpl', -- model: PolarFurbolg	 scale: 0,9  
    polarfurbolgchampion = 'nfpc', -- model: PolarFurbolg	 scale: 1,3	 selectScale: 1,5
    polarfurbolgeldershaman = 'nfpe', -- model: PolarFurbolgTracker	 scale: 1,25	 selectScale: 1,5
    polarfurbolgshaman = 'nfps', -- model: PolarFurbolgTracker	 scale: 0,9  
    polarfurbolgtracker = 'nfpt', -- model: PolarFurbolgTracker	 scale: 1,2	 selectScale: 1,5
    polarfurbolgursawarrior = 'nfpu', -- model: PolarFurbolg	 scale: 1,4	 selectScale: 1,75
    possessedgromhellscream = 'Opgh', -- model: ChaosHellscream	 scale: 1,2	 selectScale: 1,15
    powergenerator = 'npgr', -- model: PowerGenerator	 selectScale: 3,5  
    priest = 'hmpr', -- model: Priest	
    priestessofthemoon = 'Emoo', -- model: HeroMoonPriestess	 selectScale: 2,25  
    purplefelstalker = 'npfl', -- model: FelstalkerPurple	 scale: 0,8	 selectScale: 1,2
    purplefountain = 'nfnp', -- model: FountainOfPower	 selectScale: 5  
    queenofsuffering = 'ndqs', -- model: DemonessBlue	 scale: 1,5	 selectScale: 1,5
    quillbeast1 = 'nqb1', -- model: QuillBeast	 scale: 1,2	 selectScale: 1,4
    quillbeast2 = 'nqb2', -- model: QuillBeast	 scale: 1,4	 selectScale: 1,6
    quillbeast3 = 'nqb3', -- model: QuillBeast	 scale: 1,6	 selectScale: 1,8
    quillbeast4 = 'nqb4', -- model: QuillBeast	 scale: 1,75	 selectScale: 2
    quillboar = 'nrzt', -- model: Bristleback	 scale: 1,1  
    quillboarhunter = 'nqbh', -- model: Bristleback	 scale: 1,4  
    rabbit = 'necr', -- model: EasterRabbit	 selectScale: 0,9  
    raccoon = 'nrac', -- model: Raccoon	 selectScale: 0,9  
    rat = 'nrat', -- model: Rat	 selectScale: 0,9  
    razormanebrute = 'nrzb', -- model: RazorMane	 scale: 1,6  
    razormanechieftain = 'nrzg', -- model: RazorManeChief	 scale: 1,8  
    razormanemedicineman = 'nrzm', -- model: RazorManeChief	 scale: 1,3  
    razormanescout = 'nrzs', -- model: RazorMane	 scale: 1,2  
    reddragon = 'nrwm', -- model: RedDragon	 scale: 1,75	 selectScale: 2,25
    reddragonroost = 'ndrr', -- model: DragonBuilding	 scale: 1,5	 selectScale: 6,6
    reddragonwhelp = 'nrdk', -- model: RedDragonWelp	 scale: 0,7	 selectScale: 1,75
    reddrake = 'nrdr', -- model: RedDragon	 scale: 1,2	 selectScale: 2
    reefelemental = 'nrel', -- model: SeaElemental	 scale: 0,7	 selectScale: 1,6
    renegadewizard = 'nwzg', -- model: BanditMage	 scale: 1,1	 selectScale: 1,5
    revenantofthedepths = 'ndrv', -- model: RevenantOfTheWaves	 scale: 1,4  
    revenantoftheseas = 'nsrv', -- model: RevenantOfTheWaves	 scale: 1,05  
    revenantofthetides = 'ntrv', -- model: RevenantOfTheWaves	 scale: 0,9  
    rexxar = 'Orex', -- model: Rexxar	 selectScale: 2  
    riddenhippogryph = 'ehpr', -- model: RiddenHippogryph	 selectScale: 1,5  
    riderlesshorse = 'hhdl', -- model: KnightNoRider	 selectScale: 1,4  
    riderlesswyvern = 'ownr', -- model: RiderlessWyvern	 selectScale: 1,75  
    rifleman = 'hrif', -- model: Rifleman	
    robogoblintinker = 'Nrob', -- model: HeroTinker	 selectScale: 3,2  
    rocketengine = 'hrtt', -- model: WarWagon	 selectScale: 2,5  
    rockgolem = 'ngst', -- model: RockGolem	 scale: 1,05	 selectScale: 1,85
    rogue = 'nrog', -- model: Bandit	 scale: 1,3  
    roguewizard = 'nwzr', -- model: BanditMage	 scale: 0,9	 selectScale: 1,5
    rokhan = 'Orkn', -- model: HeroShadowHunter	 selectScale: 1,2  
    ruinedelvenfishingvillage0 = 'nvr0', -- model: ElvenFishVillageBuildingRuined0	 selectScale: 3,5  
    ruinedelvenfishingvillage1 = 'nvr1', -- model: ElvenFishVillageBuildingRuined1	 selectScale: 3,5  
    ruinedelvenfishingvillage2 = 'nvr2', -- model: ElvenFishVillageBuildingRuined2	 selectScale: 3,5  
    sacrificialpit = 'usap', -- model: SacrificialPit	 selectScale: 4,5  
    salamander = 'nslr', -- model: ThunderLizardSalamander	 scale: 0,95	 selectScale: 2,5
    salamanderhatchling = 'nslh', -- model: ThunderLizardSalamander	 scale: 0,6	 selectScale: 2,5
    salamanderlord = 'nsll', -- model: ThunderLizardSalamander	 scale: 1,25	 selectScale: 2,5
    salamandervizier = 'nslv', -- model: ThunderLizardVizier	 scale: 1,1	 selectScale: 2,5
    sammycube = 'zsmc', -- model: SammyCube	 selectScale: 1,2  
    samuro = 'Osam', -- model: HeroBladeMaster	 selectScale: 1,25  
    sasquatch = 'nsqt', -- model: Sasquatch	 selectScale: 1,2  
    sasquatchoracle = 'nsqo', -- model: Sasquatch	 scale: 1,35	 selectScale: 1,25
    satyr = 'nsty', -- model: Satyr	 scale: 1,15  
    satyrhellcaller = 'nsth', -- model: satyrhellcaller	 scale: 1,05	 selectScale: 1,25
    satyrshadowdancer = 'nsts', -- model: SatyrTrickster	 scale: 1,6  
    satyrsoulstealer = 'nstl', -- model: Satyr	 scale: 1,8  
    satyrtrickster = 'nsat', -- model: SatyrTrickster	
    scouttower = 'hwtw', -- model: HumanTower	 selectScale: 2,5  
    seaelemental = 'nsel', -- model: SeaElemental	 scale: 1,1	 selectScale: 1,6
    seagiant = 'nsgn', -- model: SeaGiant	 scale: 0,8	 selectScale: 2
    seagiantbehemoth = 'nsgb', -- model: SeaGiant	 scale: 1,2	 selectScale: 3
    seagianthunter = 'nsgh', -- model: SeaGiantGreen	 selectScale: 2,4  
    seal = 'nsea', -- model: Seal	
    searinox = 'nser', -- model: BlackDragon	 scale: 1,4	 selectScale: 2,25
    seaturtle = 'ntrs', -- model: SeaTurtle	 scale: 0,5	 selectScale: 2
    seaturtlehatchling = 'ntrh', -- model: SeaTurtleRange	 scale: 0,4	 selectScale: 1,5
    seawitch = 'Nngs', -- model: HeroNagaSeawitch	 selectScale: 2  
    sentryward = 'oeye', -- model: SentryWard	 selectScale: 0,75  
    serpentward1 = 'osp1', -- model: SerpentWard	 selectScale: 0,75  
    serpentward2 = 'osp2', -- model: SerpentWard	 selectScale: 0,75  
    serpentward3 = 'osp3', -- model: SerpentWard	 selectScale: 0,75  
    serpentward4 = 'osp4', -- model: SerpentWard	 selectScale: 0,75  
    shade = 'ushd', -- model: Shade	
    shadowhunter = 'Oshd', -- model: HeroShadowHunter	 selectScale: 1,2  
    shaman = 'oshm', -- model: Shaman	 selectScale: 1,15  
    shandris = 'eshd', -- model: Shandris	 scale: 1,1  
    sheep = 'nshe', -- model: Sheep	 scale: 1,2	 selectScale: 0,9
    shimmeringportal = 'hprt', -- model: ShimmeringPortal	 selectScale: 3,5  
    shrine = 'nshr', -- model: SacrificialAltar	 selectScale: 4  
    shrineofazshara = 'nnsa', -- model: ShrineOfAshjara	 scale: 0,9	 selectScale: 4,5
    siegeengine = 'hmtt', -- model: WarWagon	 selectScale: 2,5  
    siegegolem = 'nsgg', -- model: GolemStatue	 scale: 1,5	 selectScale: 2,3
    sinjostormstout = 'Nsjs', -- model: PandarenBrewmaster	 selectScale: 2  
    siren = 'nnsw', -- model: NagaSiren	
    skeletalarcher = 'nska', -- model: SkeletonArcher	
    skeletalarchersummoned = 'nsca', -- model: SkeletonArcher	
    skeletalmage = 'uskm', -- model: SkeletonMage	
    skeletalmarksman = 'nskm', -- model: SkeletonArcher	 scale: 1,3  
    skeletalorc = 'nsko', -- model: SkeletonOrc	 scale: 1,1  
    skeletalorcchampion = 'nsoc', -- model: SkeletonOrc	 scale: 1,5	 selectScale: 1,25
    skeletalorcgrunt = 'nsog', -- model: SkeletonOrc	 scale: 1,3  
    skeleton = 'nske', -- model: Skeleton	
    skeletonsummoned = 'nsce', -- model: Skeleton	
    skeletonwarrior = 'uske', -- model: Skeleton	
    skink = 'nskk', -- model: Skink	 selectScale: 0,9  
    skyfurytower = 'negm', -- model: ElvenGuardMagicTower	 selectScale: 2,5  
    slaughterhouse = 'uslh', -- model: Slaughterhouse	 selectScale: 4,25  
    sludgeflinger = 'nslf', -- model: SludgeMonster	 scale: 1,3	 selectScale: 2
    sludgeminion = 'nslm', -- model: SludgeMonster	 scale: 0,75  
    sludgemonstrosity = 'nsln', -- model: SludgeMonster	 scale: 1,8	 selectScale: 3
    snapdragon = 'nsnp', -- model: SnapDragon	 selectScale: 2  
    snapdragonmorph = 'nsbs', -- model: SnapDragon	 selectScale: 1,75  
    snowyowl = 'nsno', -- model: SnowOwl	 scale: 1,2	 selectScale: 0,8
    sorceress = 'hsor', -- model: Sorceress	
    spawninggrounds = 'nnsg', -- model: SpawningGrounds	 selectScale: 5  
    spellbreaker = 'hspt', -- model: BloodElfSpellThief	 scale: 0,8	 selectScale: 1,2
    spider = 'nspr', -- model: Spider	 scale: 0,5	 selectScale: 1,1
    spiderblack = 'nspb', -- model: SpiderBlack	 selectScale: 1,1  
    spidercrab = 'nscb', -- model: SpiderCrabCreep	 selectScale: 1,2  
    spidercrab2 = 'nsc2', -- model: SpiderCrabCreep	 scale: 1,2	 selectScale: 1,5
    spidercrab3 = 'nsc3', -- model: SpiderCrabCreep	 scale: 1,35	 selectScale: 1,72
    spiderling = 'nspd', -- model: Nerubian	 scale: 0,6	 selectScale: 1,5
    spiritbeast = 'nsw1', -- model: FelstalkerPurple	 scale: 0,8  
    spiritbeast2 = 'nsw2', -- model: FelstalkerPurple	 scale: 1,15	 selectScale: 1,7
    spiritbeast3 = 'nsw3', -- model: FelstalkerPurple	 scale: 1,4	 selectScale: 2,5
    spiritlodge = 'osld', -- model: SpiritLodge	 selectScale: 3,5  
    spiritofvengeance = 'espv', -- model: SpiritOfVengeance	 selectScale: 2  
    spiritpig = 'nspp', -- model: SpiritPig	 selectScale: 1,25  
    spiritwalker = 'ospw', -- model: spiritwalker	 selectScale: 1,15  
    spiritwalkermorph = 'ospm', -- model: spiritwalker	 selectScale: 1,15  
    spiritwolf1 = 'osw1', -- model: Spiritwolf	 scale: 0,9	 selectScale: 1,25
    spiritwolf2 = 'osw2', -- model: Spiritwolf	 scale: 1,1	 selectScale: 1,5
    spiritwolf3 = 'osw3', -- model: Spiritwolf	 scale: 1,3	 selectScale: 1,75
    spiritwyvern = 'oswy', -- model: SpiritWyvern	 selectScale: 1,75  
    spittingspider = 'nssp', -- model: SpiderBlue	 selectScale: 1,5  
    stasistraptotem = 'otot', -- model: StasisTotem	 selectScale: 0,75  
    stonemaulmagi = 'nogn', -- model: OgreMagi	 scale: 1,6	 selectScale: 1,75
    stonemaulogre = 'nogo', -- model: OgreOneHeaded	 scale: 1,6	 selectScale: 1,75
    stonemaulwarchief = 'noga', -- model: OgreOneHeadedArmored	 scale: 2,1	 selectScale: 2,2
    stormreaverapprentice = 'nsra', -- model: OrcWarlock	 scale: 0,9	 selectScale: 1,1
    stormreaverhermit = 'nsrh', -- model: OrcWarlock	 selectScale: 1,25  
    stormreavernecrolyte = 'nsrn', -- model: OrcWarlock	 scale: 1,25	 selectScale: 1,25
    stormreaverwarlock = 'nsrw', -- model: OrcWarlock	 scale: 1,5	 selectScale: 1,25
    stormwyrm = 'nstw', -- model: ThunderLizard	 scale: 1,4	 selectScale: 3
    stronghold = 'ostr', -- model: GreatHall	 selectScale: 6,6  
    succubus = 'ndqn', -- model: Demoness	
    summoner = 'nnsu', -- model: NagaSummoner	
    supportcolumn = 'nspc', -- model: SupportBeam	 selectScale: 3  
    sylvanusbanshee = 'uswb', -- model: BansheeGhost	 scale: 1,3	 selectScale: 1,3
    sylvanuswindrunner = 'Hvwd', -- model: SylvanusWindrunner	 scale: 1,1	 selectScale: 1,5
    tauren = 'otau', -- model: Tauren	 scale: 1,1	 selectScale: 1,6
    taurenchieftain = 'Otch', -- model: HeroTaurenChieftain	 scale: 1,1	 selectScale: 2
    taurentent = 'ntnt', -- model: TaurenTent	 selectScale: 2,5  
    taurentent2 = 'ntt2', -- model: TaurenTent2	 selectScale: 2,5  
    taurentotem = 'otto', -- model: TaurenTotem	 selectScale: 3,25  
    templeofthedamned = 'utod', -- model: TempleOfTheDamned	 selectScale: 4,25  
    templeoftides = 'nntt', -- model: TempleofTides	 selectScale: 5,5  
    tent = 'nten', -- model: Tent	 selectScale: 3  
    tent2 = 'ntn2', -- model: Tent1	 selectScale: 3  
    tentacle = 'nfgt', -- model: ForgottenOneTent	 selectScale: 0,75  
    tharifas = 'nthr', -- model: GreenDragon	 scale: 1,4	 selectScale: 2,25
    thecaptain = 'hcth', -- model: TheCaptain	 scale: 1,15	 selectScale: 1,2
    theshoveler = 'zshv', -- model: Shoveler	 scale: 0,85	 selectScale: 1,2
    thrall = 'Othr', -- model: Thrall	 selectScale: 2  
    thunderlizard = 'nthl', -- model: ThunderLizard	 scale: 1,15	 selectScale: 2,5
    tichondrius = 'Utic', -- model: Tichondrius	 scale: 1,15	 selectScale: 2
    tidalguardian = 'nntg', -- model: TidalGuardian	 selectScale: 3,25  
    timberwolf = 'nwlt', -- model: TimberWolf	 scale: 0,75	 selectScale: 1,1
    tinker = 'Ntin', -- model: HeroTinker	 selectScale: 2  
    tombofrelics = 'utom', -- model: TombOfRelics	 selectScale: 5,5  
    tornado = 'ntor', -- model: TornadoElemental	
    townhall = 'htow', -- model: TownHall	 selectScale: 6,3  
    transportship = 'nbot', -- model: HumanTransportShip	 selectScale: 3,5  
    treasurebox = 'nitb', -- model: IceCrownTreasureBox	 selectScale: 3,3  
    treeofages = 'etoa', -- model: TreeofLife	 scale: 1,15	 selectScale: 4,75
    treeofeternity = 'etoe', -- model: TreeofLife	 scale: 1,3	 selectScale: 4,75
    treeoflife = 'etol', -- model: TreeofLife	 selectScale: 4,75  
    trollbatrider = 'otbr', -- model: BatTroll	 selectScale: 1,75  
    trollburrow = 'otrb', -- model: TrollBurrow	 selectScale: 2,75  
    tuskarrchieftain = 'ntkc', -- model: tuskarLord	 scale: 1,25	 selectScale: 2
    tuskarrfighter = 'ntkf', -- model: tuskar	 scale: 0,75	 selectScale: 1,25
    tuskarrhealer = 'ntkh', -- model: tuskarLord	 scale: 0,75	 selectScale: 1,25
    tuskarrsorceror = 'ntks', -- model: tuskarRanged	 selectScale: 1,66  
    tuskarrspearman = 'ntka', -- model: tuskarRanged	 scale: 0,75	 selectScale: 1,25
    tuskarrtrapper = 'ntkt', -- model: tuskarRanged	 selectScale: 1,66  
    tuskarrwarrior = 'ntkw', -- model: tuskarLord	 selectScale: 1,66  
    tyrande = 'Etyr', -- model: HeroMoonPriestess	 selectScale: 2,25  
    unbrokendarkhunter = 'nubk', -- model: Unbroken	 scale: 0,55	 selectScale: 1,25
    unbrokendarkweaver = 'nubw', -- model: Unbroken	 scale: 0,7	 selectScale: 1,75
    unbrokenrager = 'nubr', -- model: Unbroken	 scale: 0,65	 selectScale: 1,5
    undeadbattleship = 'uubs', -- model: UndeadShipBattleShip	 selectScale: 4  
    undeaddestroyer = 'udes', -- model: UndeadDestroyerShip	 selectScale: 3  
    undeadgoldmine2 = 'ugol', -- model: HauntedMine	 selectScale: 5,5  
    undeadshipyard = 'ushp', -- model: UndeadShipyard	 selectScale: 4,75  
    undeadtransportship = 'ubot', -- model: UndeadTransportShip	 selectScale: 3  
    uther = 'Huth', -- model: Uther	 scale: 1,1	 selectScale: 1,1
    varimathras = 'Uvar', -- model: Tichondrius	 scale: 1,2	 selectScale: 1,75
    vengeance = 'even', -- model: Vengeance	
    vengyr = 'Uvng', -- model: HeroDreadLord	 scale: 1,15	 selectScale: 2
    viletemptress = 'ndqt', -- model: Demoness	 scale: 1,4	 selectScale: 1,4
    viletormentor = 'ndqv', -- model: DemonessBlue	 scale: 1,2	 selectScale: 1,2
    villagerkid = 'nvlk', -- model: VillagerKid	 scale: 1,2	 selectScale: 0,75
    villagerkid2 = 'nvk2', -- model: VillagerKid1	 scale: 1,2	 selectScale: 0,75
    villagerman = 'nvil', -- model: VillagerMan	 scale: 1,2  
    villagerman2 = 'nvl2', -- model: VillagerMan1	 scale: 1,2  
    villagerwoman = 'nvlw', -- model: VillagerWoman	 scale: 1,05  
    voidwalker = 'nvdw', -- model: VoidWalker	 scale: 1,15	 selectScale: 1,2
    voljin = 'ovlj', -- model: WitchDoctor	
    voodoolounge = 'ovln', -- model: VoodooLounge	 selectScale: 4,5  
    vulture = 'nvul', -- model: Vulture	
    war2warlock = 'nw2w', -- model: ChaosWarlockGreen	 selectScale: 1,15  
    warden = 'Ewar', -- model: herowarden	 selectScale: 1,5  
    wareagle1 = 'nwe1', -- model: WarEagle	 scale: 0,9	 selectScale: 1,25
    wareagle2 = 'nwe2', -- model: WarEagle	 scale: 1,1	 selectScale: 1,5
    wareagle3 = 'nwe3', -- model: WarEagle	 scale: 1,3	 selectScale: 1,75
    wargolem = 'nwrg', -- model: GolemStatue	 scale: 1,25	 selectScale: 1,9
    warmill = 'ofor', -- model: WarMill	 selectScale: 3,5  
    warriorarachnathid = 'nanw', -- model: ArchnathidGreen	 scale: 0,9	 selectScale: 1,6
    watcher = 'nwat', -- model: watcher	
    watcherward = 'nwad', -- model: WatcherWard	 selectScale: 0,75  
    watchtower = 'owtw', -- model: WatchTower	 selectScale: 2,5  
    waterelemental1 = 'hwat', -- model: WaterElemental	 scale: 0,9	 selectScale: 1,6
    waterelemental2 = 'hwt2', -- model: WaterElemental	 scale: 1,1	 selectScale: 1,6
    waterelemental3 = 'hwt3', -- model: WaterElemental	 scale: 1,3	 selectScale: 1,6
    waterpenguin = 'npnw', -- model: Penguin	 selectScale: 0,9  
    watersheep = 'nshw', -- model: Sheep	 scale: 1,2	 selectScale: 0,9
    wateryminioncliffrunner = 'ncfs', -- model: MurgulTideWarrior	 scale: 0,8	 selectScale: 0,8
    wateryminionsnarecaster = 'nsns', -- model: MurgulShadowCaster	 scale: 1,1	 selectScale: 1,1
    wateryminiontidewarrior = 'ntws', -- model: MurgulTideWarrior	
    waygate = 'nwgt', -- model: Waygate	 selectScale: 3,5  
    wendigo1 = 'nwen', -- model: Wendigo	 scale: 0,9	 selectScale: 1,2
    wendigoshaman = 'nwns', -- model: WendigoShaman	 scale: 1,2	 selectScale: 1,2
    whitedirewolf = 'nwwd', -- model: WhiteWolf	 scale: 1,45	 selectScale: 2
    whitewolf = 'nwwf', -- model: WhiteWolf	 selectScale: 1,25  
    windrider = 'owyv', -- model: WyvernRider	 selectScale: 1,75  
    windserpent = 'nws1', -- model: WindSerpent	 scale: 1,2	 selectScale: 1,25
    wisp = 'ewsp', -- model: Wisp	
    witchdoctor = 'odoc', -- model: WitchDoctor	
    wolfrider = 'orai', -- model: WolfRider	 selectScale: 1,6  
    workshop = 'harm', -- model: Workshop	 selectScale: 4,25  
    wraith = 'ngh2', -- model: BansheeGhost	 scale: 1,4  
    wyverncage1 = 'nwc1', -- model: WyvernCage	 selectScale: 3,3  
    wyverncage2 = 'nwc2', -- model: WyvernCage2	 selectScale: 3,3  
    zergling = 'zzrg', -- model: zergling	
    ziggurat = 'uzig', -- model: Ziggurat	 selectScale: 4,25  
    ziggurat1 = 'uzg1', -- model: Ziggurat	 selectScale: 4,25  
    zombie = 'nzom', -- model: Zombie	 scale: 1,15  
    zoneindicator = 'nzin', -- model: IntentionallyLeftBlank	
}

return UnitIds
