local ID = require('stdlib.objediting.stdlibids')
local UnitIds = require('stdlib.assets.UnitIds')
local AbilityIds = require('stdlib.assets.AbilityIds')
local TargetsAllowed = require('stdlib.objediting.TargetsAllowed')
local Icons = require('stdlib.ui.icons')

local abil = AbilityDefinitionDefend:new(ID.Abilities.UnitEnterLeaveDectect)
abil:setName('Leave Dectect')
abil:setEditorSuffix('(UnitTracker)')
abil:setArtCaster('')
abil:setIconNormal('')
abil:setRace(Race.Unknown)

abil = AbilityDefinitionRootAncients:new(ID.Abilities.RootEnabler)

abil = AbilityDefinitionPermanentInvisibility:new(ID.Abilities.DisableAutoAcquireAttackTargets)
abil:setAutoAcquireAttackTargets(1, false)
abil:setDurationNormal(1, -1)
abil:setDurationHero(1, -1)

local u = UnitDefinition:new(ID.Units.DummyUnit, UnitIds.wisp)
u:setName('Effect Dummy Unit')
u:setUpgradesUsed('')
u:setStructuresBuilt('')
u:setManaRegeneration(0.1)
u:setManaInitialAmount(1000)
u:setManaMaximum(1000)
u:setCollisionSize(0.0)
u:setRace(Race.Commoner)
u:setFoodCost(0)
u:setArmorType(ArmorType.Divine)
u:setIconGameInterface(Icons.bTNTemp)
u:setSpeedBase(522)
u:setModelFile('dummy.mdl')
u:setAnimationBlendTimeseconds(0.0)
u:setAnimationCastBackswing(0.0)
u:setMaximumPitchAngledegrees(0.0)
u:setMaximumRollAngledegrees(0.0)
u:setArtSpecial('')
u:setProjectileImpactZ(0.0)
u:setProjectileLaunchZ(0.0)
u:setNameEditorSuffix('(Basics)')
u:setSightRadiusDay(1)
u:setSightRadiusNight(1)
u:setUnitClassification('_')
u:setPropulsionWindowdegrees(1.0)
u:setTooltipBasic('')
u:setAttacksEnabled(AttacksEnabled.AttackOneOnly)
u:setAttack1AnimationBackswingPoint(0)
u:setAttack1AnimationDamagePoint(0)
u:setAttack1CooldownTime(0)
u:setAttack1AttackType(AttackType.Unknown)
u:setAttack1DamageBase(-1)
u:setAttack1DamageNumberofDice(1)
u:setAttack1DamageSidesperDie(1)
u:setAttack1ProjectileSpeed(2147483647)
u:setAttack1Range(2147483647)
u:setAttack1TargetsAllowed(table.concat({
    TargetsAllowed.air, TargetsAllowed.debris, TargetsAllowed.ground, TargetsAllowed.invulnerable,
    TargetsAllowed.item_t, TargetsAllowed.structure, TargetsAllowed.vulnerable, TargetsAllowed.ward,
}, ','))
u:setAttack1WeaponSound(WeaponSound.Nothing)
u:setAttack1WeaponType(WeaponType.Instant)
u:setAcquisitionRange(2147483647)
u:setNormalAbilities(table.concat({
    AbilityIds.invulnerable, AbilityIds.locust, ID.Abilities.DisableAutoAcquireAttackTargets,
}))
