local OrderStrings = {
    'absorb', 'acidbomb', 'acolyteharvest', 'whirlwind', 'ambush', 'ancestralspirit', 'ancestralspirittarget',
    'animatedead', 'antimagicshell', 'webon', 'weboff', 'web', 'attributemodskill', 'auraunholy', 'auravampiric',
    'autodispel', 'autodispeloff', 'autodispelon', 'autoentangle', 'autoentangleinstant', 'wateryminion',
    'waterelemental', 'avatar', 'avengerform', 'awaken', 'banish', 'barkskin', 'barkskinoff', 'barkskinon',
    'battleroar', 'battlestations', 'bearform', 'berserk', 'blackarrow', 'blackarrowoff', 'blackarrowon', 'blight',
    'blink', 'blizzard', 'bloodlust', 'bloodlustoff', 'bloodluston', 'board', 'breathoffire', 'breathoffrost', 'ward',
    'burrow', 'cannibalize', 'carrionscarabs', 'carrionscarabsinstant', 'carrionscarabsoff', 'carrionscarabson',
    'carrionswarm', 'chainlightning', 'channel', 'charm', 'chemicalrage', 'cloudoffog', 'clusterrockets', 'coldarrows',
    'coldarrowstarg', 'controlmagic', 'corporealform', 'corrosivebreath', 'coupleinstant', 'coupletarget',
    'creepanimatedead', 'creepdevour', 'creepheal', 'creephealoff', 'creephealon', 'creepthunderbolt',
    'creepthunderclap', 'cripple', 'curse', 'curseoff', 'curseon', 'cyclone', 'darkconversion', 'darkportal',
    'darkritual', 'darksummoning', 'deathanddecay', 'deathcoil', 'deathpact', 'windwalk', 'defend', 'detectaoe',
    'detonate', 'devour', 'devourmagic', 'disassociate', 'disenchant', 'dismount', 'dispel', 'divineshield', 'doom',
    'drain', 'dreadlordinferno', 'dropitem', 'drunkenhaze', 'earthquake', 'eattree', 'elementalfury', 'wispharvest',
    'ensnareoff', 'ensnareon', 'entangle', 'entangleinstant', 'entanglingroots', 'etherealform', 'evileye',
    'faeriefire', 'faeriefireoff', 'faeriefireon', 'fanofknives', 'farsight', 'fingerofdeath', 'firebolt',
    'flamestrike', 'flamingarrows', 'flamingarrowstarg', 'flamingattack', 'flamingattacktarg', 'flare', 'forceboard',
    'forceofnature', 'forkedlightning', 'freezingbreath', 'frenzy', 'frenzyoff', 'frenzyon', 'frostarmor',
    'frostarmoroff', 'frostarmoron', 'frostnova', 'getitem', 'gold2lumber', 'grabtree', 'harvest', 'heal',
    'healingspray', 'healingward', 'healingwave', 'healoff', 'healon', 'hex', 'voodoo', 'holybolt', 'howlofterror',
    'humanbuild', 'immolation', 'impale', 'incineratearrow', 'incineratearrowoff', 'incineratearrowon', 'inferno',
    'innerfire', 'innerfireoff', 'innerfireon', 'instant', 'invisibility', 'lavamonster', 'lightningshield', 'load',
    'loadarcher', 'loadcorpse', 'loadcorpseinstant', 'locustswarm', 'lumber2gold', 'magicdefense', 'magicleash',
    'magicundefense', 'manaburn', 'manaflareoff', 'manaflareon', 'manashieldoff', 'manashieldon', 'massteleport',
    'mechanicalcritter', 'metamorphosis', 'militia', 'militiaconvert', 'militiaoff', 'militiaunconvert', 'mindrot',
    'mirrorimage', 'monsoon', 'mount', 'mounthippogryph', 'vengeanceoff', 'nagabuild', 'neutraldetectaoe',
    'neutralinteract', 'neutralspell', 'nightelfbuild', 'orcbuild', 'parasite', 'parasiteoff', 'parasiteon', 'patrol',
    'phaseshift', 'phaseshiftinstant', 'phaseshiftoff', 'phaseshifton', 'phoenixfire', 'phoenixmorph', 'poisonarrows',
    'poisonarrowstarg', 'polymorph', 'possession', 'preservation', 'purge', 'rainofchaos', 'rainoffire', 'raisedead',
    'raisedeadoff', 'raisedeadon', 'ravenform', 'recharge', 'rechargeoff', 'rechargeon', 'rejuvination', 'renew',
    'renewoff', 'renewon', 'repair', 'repairoff', 'repairon', 'replenish', 'replenishlife', 'replenishlifeoff',
    'replenishlifeon', 'replenishmana', 'replenishmanaoff', 'replenishmanaon', 'replenishoff', 'replenishon',
    'request_hero', 'requestsacrifice', 'restoration', 'restorationoff', 'restorationon', 'resumebuild',
    'resumeharvesting', 'resurrection', 'returnresources', 'revenge', 'revive', 'roar', 'robogoblin', 'root',
    'sacrifice', 'sanctuary', 'scout', 'selfdestruct', 'selfdestructoff', 'selfdestructon', 'sentinel', 'setrally',
    'shadowsight', 'shadowstrike', 'shockwave', 'silence', 'sleep', 'slow', 'slowoff', 'slowon', 'vengeanceon',
    'soulburn', 'soulpreservation', 'spellshield', 'spellshieldaoe', 'spellsteal', 'spellstealoff', 'spellstealon',
    'spies', 'spiritlink', 'spiritofvengeance', 'spirittroll', 'spiritwolf', 'stampede', 'standdown', 'starfall',
    'stasistrap', 'steal', 'stomp', 'stoneform', 'volcano', 'submerge', 'summonfactory', 'summongrizzly',
    'summonphoenix', 'summonquillbeast', 'summonwareagle', 'tankdroppilot', 'tankloadpilot', 'tankpilot', 'taunt',
    'thunderbolt', 'thunderclap', 'tornado', 'townbelloff', 'townbellon', 'tranquility', 'transmute', 'unavatar',
    'unavengerform', 'unbearform', 'unburrow', 'uncoldarrows', 'uncorporealform', 'undeadbuild', 'undefend',
    'undivineshield', 'unetherealform', 'unflamingarrows', 'unflamingattack', 'unholyfrenzy', 'unimmolation', 'unload',
    'unloadall', 'unloadallcorpses', 'unloadallinstant', 'unpoisonarrows', 'unravenform', 'unrobogoblin', 'unroot',
    'unstableconcoction', 'unstoneform', 'unsubmerge', 'unsummon', 'unwindwalk', 'vengeance', 'vengeanceinstant',
}

return OrderStrings
